from __future__ import annotations

from pathlib import Path
from typing import Any


class ModelPoolError(RuntimeError):
    pass


CATALOG: list[dict[str, Any]] = [
    {
        "key": "openai",
        "name": "OpenAI",
        "region": "国外",
        "base_url": "https://api.openai.com/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "ChatGPT 官方",
        "models": [
            "gpt-5", "gpt-5-mini", "gpt-5-nano",
            "gpt-4o", "gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini",
            "o3", "o3-mini", "o4-mini",
        ],
    },
    {
        "key": "anthropic",
        "name": "Anthropic Claude",
        "region": "国外",
        "base_url": "https://api.anthropic.com",
        "api_style": "anthropic",
        "key_required": True,
        "free": False,
        "supported": False,
        "notes": "非 OpenAI 协议,天枢不可直连,仅供外部项目配置",
        "models": ["claude-opus-4-1", "claude-sonnet-4-5", "claude-haiku-4-5"],
    },
    {
        "key": "xai",
        "name": "xAI Grok",
        "region": "国外",
        "base_url": "https://api.x.ai/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "X 平台 Grok 系列",
        "models": ["grok-4", "grok-4-mini", "grok-4-fast", "grok-3", "grok-3-mini"],
    },
    {
        "key": "google",
        "name": "Google Gemini",
        "region": "国外",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "api_style": "openai",
        "key_required": True,
        "free": True,
        "supported": True,
        "notes": "官方 OpenAI 兼容端点",
        "models": ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.0-flash"],
    },
    {
        "key": "deepseek",
        "name": "DeepSeek",
        "region": "国内",
        "base_url": "https://api.deepseek.com/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "",
        "models": ["deepseek-chat", "deepseek-reasoner"],
    },
    {
        "key": "qwen",
        "name": "阿里通义 Qwen",
        "region": "国内",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "DashScope 兼容模式",
        "models": ["qwen3-max", "qwen3-plus", "qwen3-turbo", "qwen-max", "qwen-plus", "qwen-turbo", "qwen2.5-72b-instruct"],
    },
    {
        "key": "zhipu",
        "name": "智谱 GLM",
        "region": "国内",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "api_style": "openai",
        "key_required": True,
        "free": True,
        "supported": True,
        "notes": "GLM 系列,flash 档免费",
        "models": ["glm-4.5", "glm-4.5-air", "glm-4.6", "glm-4-plus", "glm-4-flash"],
    },
    {
        "key": "moonshot",
        "name": "月之暗面 Kimi",
        "region": "国内",
        "base_url": "https://api.moonshot.cn/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "Kimi K2 系列",
        "models": ["kimi-k2-0905", "kimi-k2-thinking", "kimi-k2-0711-preview", "moonshot-v1-128k"],
    },
    {
        "key": "baidu",
        "name": "百度文心 ERNIE",
        "region": "国内",
        "base_url": "https://qianfan.baidubce.com/v2",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "千帆 V2",
        "models": ["ernie-4.0-8k", "ernie-4.0-turbo-8k", "ernie-3.5-8k", "ernie-speed-8k"],
    },
    {
        "key": "hunyuan",
        "name": "腾讯混元",
        "region": "国内",
        "base_url": "https://api.hunyuan.cloud.tencent.com/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "",
        "models": ["hunyuan-turbo", "hunyuan-pro", "hunyuan-standard", "hunyuan-lite"],
    },
    {
        "key": "volcengine",
        "name": "字节豆包",
        "region": "国内",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "火山方舟 Ark",
        "models": ["doubao-1-5-pro-32k-250115", "doubao-1-5-lite-32k-250115", "doubao-seed-1-6"],
    },
    {
        "key": "minimax",
        "name": "MiniMax",
        "region": "国内",
        "base_url": "https://api.minimaxi.com/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "",
        "models": ["MiniMax-Text-01", "abab6.5s-chat", "abab7-chat"],
    },
    {
        "key": "spark",
        "name": "讯飞星火",
        "region": "国内",
        "base_url": "https://spark-api-open.xf-yun.com/v1",
        "api_style": "openai",
        "key_required": True,
        "free": False,
        "supported": True,
        "notes": "",
        "models": ["generalv4.0", "generalv3.5", "4.0Ultra", "4.0Turbo"],
    },
    {
        "key": "ollama",
        "name": "Ollama 本地",
        "region": "本地",
        "base_url": "http://localhost:11434/v1",
        "api_style": "openai",
        "key_required": False,
        "free": True,
        "supported": True,
        "notes": "本地开源模型,无需 Key",
        "models": ["llama3.3", "qwen3", "deepseek-r1", "gemma3", "mistral", "phi4"],
    },
    {
        "key": "agnes",
        "name": "Sapiens AI / Agnes",
        "region": "国外",
        "base_url": "https://apihub.agnes-ai.com/v1",
        "api_style": "openai",
        "key_required": True,
        "free": True,
        "supported": True,
        "notes": "新加坡本土模型,免费配额,OpenAI 兼容",
        "models": ["agnes-2.5-flash", "agnes-2.0-flash", "agnes-1.5-flash", "agnes-image-2.1-flash", "agnes-video-v2.0"],
    },
]

VENDOR_MODELS_PATH = Path(__file__).resolve().parent.parent.parent.parent / "config" / "models.json"


def default_catalog() -> dict[str, dict[str, Any]]:
    return {v["key"]: dict(v) for v in CATALOG}


def model_tags_to_name(mid: str) -> str:
    return mid